services:
  postgres:
    container_name: postgres_db
    build:
      context: .
    volumes:
      - ./persist-storage:/var/lib/postgresql/data
      - certs-volume:/var/lib/postgresql/certs
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/certs/postgresdb.crt -c ssl_key_file=/var/lib/postgresql/certs/postgresdb.key
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5430:5430"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - backend

  copy-certs:
    image: busybox
    container_name: copy_certs
    command: ["sh", "-c", "cp /var/lib/postgresql/certs/* /certs"]
    volumes:
      - certs-volume:/var/lib/postgresql/certs
      - ./certs:/certs
    networks:
      - backend
    depends_on:
      - postgres

volumes:
  certs-volume:

networks:
  backend:
